# page title and description
title: "Abdullah Shafqat"
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/abdullah_shafqat" 
url: "https://abdullah_shafqat.github.io"
repository: "abdullahshafqat21/abdullah_shafqat.github.io"
twitter_username: username
github_username: username


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - gjekyll-seo-tag